# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: block.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import primitive_pb2 as primitive__pb2
import transaction_pb2 as transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='block.proto',
  package='iroha.protocol',
  syntax='proto3',
  serialized_pb=_b('\n\x0b\x62lock.proto\x12\x0eiroha.protocol\x1a\x0fprimitive.proto\x1a\x11transaction.proto\"\xf7\x01\n\x05\x42lock\x12.\n\x07payload\x18\x01 \x01(\x0b\x32\x1d.iroha.protocol.Block.Payload\x12-\n\nsignatures\x18\x02 \x03(\x0b\x32\x19.iroha.protocol.Signature\x1a\x8e\x01\n\x07Payload\x12\x31\n\x0ctransactions\x18\x01 \x03(\x0b\x32\x1b.iroha.protocol.Transaction\x12\x11\n\ttx_number\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\x04\x12\x17\n\x0fprev_block_hash\x18\x05 \x01(\x0c\x12\x14\n\x0c\x63reated_time\x18\x06 \x01(\x04\x62\x06proto3')
  ,
  dependencies=[primitive__pb2.DESCRIPTOR,transaction__pb2.DESCRIPTOR,])




_BLOCK_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='iroha.protocol.Block.Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transactions', full_name='iroha.protocol.Block.Payload.transactions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tx_number', full_name='iroha.protocol.Block.Payload.tx_number', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='iroha.protocol.Block.Payload.height', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='prev_block_hash', full_name='iroha.protocol.Block.Payload.prev_block_hash', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created_time', full_name='iroha.protocol.Block.Payload.created_time', index=4,
      number=6, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=173,
  serialized_end=315,
)

_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='iroha.protocol.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='iroha.protocol.Block.payload', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='signatures', full_name='iroha.protocol.Block.signatures', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_BLOCK_PAYLOAD, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=315,
)

_BLOCK_PAYLOAD.fields_by_name['transactions'].message_type = transaction__pb2._TRANSACTION
_BLOCK_PAYLOAD.containing_type = _BLOCK
_BLOCK.fields_by_name['payload'].message_type = _BLOCK_PAYLOAD
_BLOCK.fields_by_name['signatures'].message_type = primitive__pb2._SIGNATURE
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,), dict(

  Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
    DESCRIPTOR = _BLOCK_PAYLOAD,
    __module__ = 'block_pb2'
    # @@protoc_insertion_point(class_scope:iroha.protocol.Block.Payload)
    ))
  ,
  DESCRIPTOR = _BLOCK,
  __module__ = 'block_pb2'
  # @@protoc_insertion_point(class_scope:iroha.protocol.Block)
  ))
_sym_db.RegisterMessage(Block)
_sym_db.RegisterMessage(Block.Payload)


# @@protoc_insertion_point(module_scope)
